import numpy as np
import matplotlib.pyplot as plt
import argparse
import os


def plot_heatmap_simple(filename):
    """
    Reads coordinate and potential data from a file and plots a 2D heatmap.
    """
    # 1. Load the data
    try:
        # Check if the file exists before attempting to load
        if not os.path.exists(filename):
            print(f"Error: Could not find the file '{
                  filename}'. Please check the path.")
            return

        data = np.loadtxt(filename)
    except Exception as e:
        print(f"Error loading file '{filename}': {e}")
        return

    # 2. Safety Checks
    if data.size == 0:
        print("Error: The data file is empty.")
        return

    # If the file has only one point, it loads as a 1D array of shape (3,).
    # We explicitly check for the expected number of dimensions.
    if data.ndim == 1 and data.size != 0:
        print("Error: Data file only has one line. Need a full grid of data.")
        return

    # 3. Extract columns: Theta (col 0), Phi (col 1), Value (col 2)
    # The previous IndexError is now avoided by the safety checks above.
    theta_flat = data[:, 0]
    phi_flat = data[:, 1]
    values_flat = data[:, 2]

    # 4. Auto-detect Grid Dimensions
    unique_theta = np.unique(theta_flat)
    unique_phi = np.unique(phi_flat)

    n_th = len(unique_theta)
    n_ph = len(unique_phi)

    print(f"Detected Grid: nTh={n_th}, nPh={
          n_ph} (Total points: {len(values_flat)})")

    if n_th * n_ph != len(values_flat):
        print("Error: Grid dimensions do not match the number of data points. Data may be irregular or corrupted.")
        return

    # 5. Reshape Data for Plotting
    Z = values_flat.reshape((n_th, n_ph))

    # Create 2D grid for axes (converted to degrees for readability)
    Phi_grid, Theta_grid = np.meshgrid(
        np.degrees(unique_phi), np.degrees(unique_theta))

    # 6. Plot
    plt.figure(figsize=(10, 6))

    cp = plt.pcolormesh(Phi_grid, Theta_grid, Z,
                        shading='auto', cmap='viridis')

    cbar = plt.colorbar(cp)
    cbar.set_label('Potential (V)')

    plt.xlabel('Phi (Longitude) [Degrees]')
    plt.ylabel('Theta (Latitude) [Degrees]')
    plt.title(f'Potential Heatmap from {os.path.basename(filename)}')

    # Invert Y axis so Theta=0 (North Pole) is at the top
    plt.gca().invert_yaxis()

    plt.tight_layout()
    plt.show()

# --- Command Line Argument Handling ---


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Plot a 2D heatmap from coordinate data generated by C++ printWithCoords.",
        formatter_class=argparse.RawTextHelpFormatter
    )

    # Define the -i flag for input file
    parser.add_argument(
        '-i', '--input',
        type=str,
        default='../data/solvedPotential.txt',  # Default path if flag is omitted
        help='Path to the input file containing theta, phi, and potential data.'
    )

    args = parser.parse_args()

    # Run the plotting function with the provided file path
    plot_heatmap_simple(args.input)
